# PURL configuration for https://purl.brain-bican.org/ontology/hbao
# Human Brain Atlas Ontology (HBAO)

idspace: HBA
base_url: /ontology/hbao


products:
# https://purl.brain-bican.org/ontology/hbao/hbao.owl
- hbao.owl: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/main/hbao.owl
- hbao.obo: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/main/hbao.obo
- hbao.json: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/main/hbao.obo

term_browser: custom
example_terms:
- HBA_0000000

base_redirect: https://github.com/brain-bican/human_brain_atlas_ontology

entries:

# OLS resolution for HBA Terms
- regex: ^/ontology/hbao/HBA_(\d+)$
  replacement: https://www.ebi.ac.uk/ols4/ontologies/hba/terms/https%253A%252F%252Fpurl.brain-bican.org%252Fontology%252Fhbao%252FHBA_$1
  tests:
  - from: /hbao/HBA_4697
    to: https://www.ebi.ac.uk/ols4/ontologies/hba/terms/https%253A%252F%252Fpurl.brain-bican.org%252Fontology%252Fhbao%252FHBA_4697
    
# https://purl.brain-bican.org/ontology/hbao/hbao-base.owl
- exact: /hbao-base.owl
  replacement: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/main/hbao-base.owl

# https://purl.brain-bican.org/ontology/hbao/latest/hbao.owl
- prefix: /latest/
  replacement: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/main/

# https://purl.brain-bican.org/ontology/hbao/releases/2022-11-02/hbao.owl
- regex: ^/ontology/hbao/releases/(.*)/hbao\.owl$
  replacement: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/$1/hbao.owl
  tests:
  - from: /hbao/releases/2022-11-02/hbao.owl
    to: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/2022-11-02/hbao.owl


## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/brain-bican/human_brain_atlas_ontology/main/
