# PURL configuration for http://purl.bican.org/ontology/pcl

idspace: PCL
base_url: /ontology/pcl

products:
- pcl.owl: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl.owl
- pcl.obo: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl.obo
- pcl.json: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl.json

term_browser: ols
example_terms:
- PCL_0011124

entries:

- exact: /pcl-base.owl
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/pcl-base.owl

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v
  tests:
    - from: /releases/2022-01-24/
      to: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v2022-01-24/
  
- exact: /bds/kg
  replacement: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:7472/browser
  
- exact: /bds/api
  replacement: http://ec2-3-143-113-50.us-east-2.compute.amazonaws.com:8484/bds/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/master/
