# PURL configuration for http://purl.bican.org/bican/

idspace: BICAN
base_url: /bican

term_browser: custom


### Entries
entries:

- exact: /home.html
  replacement: https://github.com/brain-bican/purl.bican.org/
