# PURL configuration for http://purl.bican.org/taxonomy/CCN201912131

idspace: CCN201912131
base_url: /taxonomy/CCN201912131

products:
- CCN201912131.json: https://raw.githubusercontent.com/AllenInstitute/MOp_taxonomies_ontology/main/humanM1_CCN201912131/updated_dendrogram_CCN201912131.json

base_redirect: https://knowledge.brain-map.org/celltypes/CCN201912131

term_browser: custom

entries:

- exact: /CCN201912131.json
  replacement: https://raw.githubusercontent.com/AllenInstitute/MOp_taxonomies_ontology/main/humanM1_CCN201912131/updated_dendrogram_CCN201912131.json

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v
  tests:
    - from: /releases/2022-01-24/
      to: https://raw.githubusercontent.com/obophenotype/provisional_cell_ontology/v2022-01-24/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://github.com/AllenInstitute/MOp_taxonomies_ontology/tree/main/humanM1_CCN201912131/