# PURL configuration for https://purl.brain-bican.org/taxonomy/CCN202210140

idspace: CCN202210140
base_url: /taxonomy/CCN202210140

products:
- CCN202210140.csv: https://raw.githubusercontent.com/hkir-dev/whole_human_brain_ontology/main/src/dendrograms/nomenclature_table_CS202210140.csv

base_redirect: https://github.com/hkir-dev/whole_human_brain_ontology

entries:

- exact: /CCN202210140.csv
  replacement: https://raw.githubusercontent.com/hkir-dev/whole_human_brain_ontology/main/src/dendrograms/nomenclature_table_CS202210140.csv

- exact: /cell_to_cell_set_assignments.csv
  replacement: https://github.com/hkir-dev/whole_human_brain_ontology/raw/main/src/cellxgene/h5ad-downloads/adult-human-brain_v1.zip
