# PURL configuration for http://purl.brain-bican.org/taxonomy/CCN202210140

idspace: CCN202210140
base_url: /taxonomy/CCN202210140

products:
- CCN202210140.json: https://raw.githubusercontent.com/AllenInstitute/MOp_taxonomies_ontology/main/marmosetM1_CCN202210140/updated_dendrogram_CCN202210140.json

base_redirect: https://knowledge.brain-map.org/celltypes/CCN202210140

entries:

- exact: /CCN202210140.json
  replacement: https://raw.githubusercontent.com/AllenInstitute/MOp_taxonomies_ontology/main/marmosetM1_CCN202210140/updated_dendrogram_CCN202210140.json