####
#### WARNING: WIP
#### This playbook is for ??.??.
####  * Add remote logging to an already established server on S3.
####
---
- hosts: all
  remote_user: ubuntu
  become: yes
  roles:
    - role: logrotate-to-s3
      var_s3_path: "obo/purl"
      var_name_prefix: ""
      var_s3_push_credentials: "~/.s3cfg"
      s3_bucket: "obo-service-logs"
      target_service: "apache2"
